-- Migration: 20260610_festival_dates_and_art
-- Adds dates_estimated flag and vector_art column to festivals table.
-- Run in Supabase SQL editor.

-- dates_estimated: true when start_date/end_date are algorithmically estimated
-- (not yet officially announced), so the UI can show "~August 2026" instead
-- of a precise date that might be wrong.
alter table festivals
  add column if not exists dates_estimated boolean default false,
  add column if not exists vector_art      text;      -- raw SVG generated by Claude

-- Index for quickly finding festivals with missing art or estimated dates
create index if not exists idx_festivals_dates_estimated
  on festivals (dates_estimated) where dates_estimated = true;

-- Helpful view for the dashboard showing upcoming festivals with date status
create or replace view v_upcoming_festivals as
  select
    id,
    slug,
    name,
    city,
    state,
    start_date,
    end_date,
    dates_estimated,
    tags,
    accent_color,
    hero_image_url,
    vector_art,
    is_active
  from festivals
  where is_active = true
    and (start_date is null or start_date >= current_date - interval '30 days')
  order by start_date asc nulls last, name;
