-- ============================================================
-- Soundcheck — Supabase Schema
-- Run this in the Supabase SQL editor to initialize the DB
-- ============================================================

-- Enable extensions
create extension if not exists "pg_trgm";      -- full-text fuzzy search
create extension if not exists "unaccent";      -- normalize accented artist names
create extension if not exists "uuid-ossp";    -- uuid generation

-- ============================================================
-- FESTIVALS
-- ============================================================
create table if not exists festivals (
  id            uuid primary key default uuid_generate_v4(),
  slug          text unique not null,              -- lollapalooza-chicago
  name          text not null,                     -- Lollapalooza
  city          text,
  state         text,
  country       text default 'US',
  venue         text,
  timezone      text,                              -- IANA tz, e.g. 'America/Chicago' (added v2.3.3) — set times are stored local to this
  start_date    date,
  end_date      date,
  website_url   text,
  wikipedia_url text,
  description   text,
  tags          text[] default '{}',               -- ['rock', 'multi-genre', 'outdoor', 'annual']
  instagram_handle text,
  x_handle      text,
  accent_color  text,                              -- hex for festival theming, e.g. '#FF4500'
  hero_image_url text,
  logo_url      text,
  dates_estimated boolean default false,           -- true = start/end are estimates, not yet announced (added 20260610)
  vector_art    text,                              -- raw SVG generated by Claude (added 20260610)
  latitude      double precision,                  -- venue coordinate, geocoded via Nominatim (added v2.3.4)
  longitude     double precision,
  geocoded_at   timestamptz,                       -- when lat/lng were resolved; doubles as the geocode cache key
  is_active     boolean default true,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- ============================================================
-- ARTISTS
-- ============================================================
create table if not exists artists (
  id              uuid primary key default uuid_generate_v4(),
  slug            text unique not null,
  name            text not null,
  bio             text,
  genres          text[] default '{}',
  origin_city     text,
  origin_country  text,
  website_url     text,
  spotify_id      text unique,
  apple_music_id  text,
  spotify_url     text,
  apple_music_url text,
  spotify_followers bigint,
  spotify_popularity int,                          -- 0–100
  preview_url     text,                            -- 30s Spotify preview
  image_url       text,
  header_image_url text,
  tags            text[] default '{}',
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ============================================================
-- LINEUPS (festival × artist join)
-- ============================================================
create table if not exists lineups (
  id            uuid primary key default uuid_generate_v4(),
  festival_id   uuid references festivals(id) on delete cascade,
  artist_id     uuid references artists(id) on delete cascade,
  year          int not null,
  stage         text,                              -- Main Stage, Perry's, etc.
  day           date,
  set_time_start time,                             -- local to festivals.timezone
  set_time_end   time,
  is_headliner  boolean default false,
  source        text,                              -- provenance/trust (added v2.3.3): official|wikipedia|ticketmaster|songkick|setlistfm|ocr|estimated
  created_at    timestamptz default now(),
  -- Set-grain uniqueness (v2.3.6): one row per set, so an artist can play
  -- multiple sets. NULLS NOT DISTINCT keeps null-day/null-time scraped rows idempotent.
  constraint lineups_slot_key unique nulls not distinct (festival_id, artist_id, year, day, set_time_start)
);

-- ============================================================
-- MEDIA (photos per festival, sourced from Unsplash)
-- ============================================================
create table if not exists media (
  id              uuid primary key default uuid_generate_v4(),
  festival_id     uuid references festivals(id) on delete cascade,
  unsplash_id     text,
  url_regular     text,
  url_thumb       text,
  url_full        text,
  alt_text        text,
  photographer    text,
  photographer_url text,
  credit_html     text,                            -- required Unsplash attribution
  created_at      timestamptz default now()
);

-- ============================================================
-- SOCIAL POSTS (synced from IG + X per festival)
-- ============================================================
create table if not exists social_posts (
  id              uuid primary key default uuid_generate_v4(),
  festival_id     uuid references festivals(id) on delete cascade,
  platform        text not null check (platform in ('instagram', 'x')),
  post_id         text not null,
  post_url        text,
  content         text,
  media_url       text,
  media_type      text,                            -- image, video, carousel
  posted_at       timestamptz,
  like_count      int,
  comment_count   int,
  synced_at       timestamptz default now(),
  unique (platform, post_id)
);

-- ============================================================
-- FUN FACTS (AI-generated per festival × year)
-- ============================================================
create table if not exists fun_facts (
  id              uuid primary key default uuid_generate_v4(),
  festival_id     uuid references festivals(id) on delete cascade,
  year            int not null,
  facts           jsonb not null,                  -- array of {fact: string, category: string}
  generated_at    timestamptz default now(),
  model_version   text,
  unique (festival_id, year)
);

-- ============================================================
-- TAGS (normalized tag registry for filtering)
-- ============================================================
create table if not exists tags (
  id    uuid primary key default uuid_generate_v4(),
  slug  text unique not null,
  label text not null,
  type  text check (type in ('genre', 'vibe', 'format', 'region', 'season'))
);

-- Seed core tags
insert into tags (slug, label, type) values
  ('multi-genre', 'Multi-Genre', 'genre'),
  ('electronic', 'Electronic', 'genre'),
  ('hip-hop', 'Hip-Hop', 'genre'),
  ('rock', 'Rock', 'genre'),
  ('indie', 'Indie', 'genre'),
  ('edm', 'EDM', 'genre'),
  ('country', 'Country', 'genre'),
  ('jazz', 'Jazz', 'genre'),
  ('outdoor', 'Outdoor', 'format'),
  ('camping', 'Camping', 'format'),
  ('urban', 'Urban', 'format'),
  ('multi-day', 'Multi-Day', 'format'),
  ('annual', 'Annual', 'vibe'),
  ('flagship', 'Flagship', 'vibe'),
  ('midwest', 'Midwest', 'region'),
  ('southwest', 'Southwest', 'region'),
  ('southeast', 'Southeast', 'region'),
  ('west-coast', 'West Coast', 'region'),
  ('northeast', 'Northeast', 'region'),
  ('spring', 'Spring', 'season'),
  ('summer', 'Summer', 'season'),
  ('fall', 'Fall', 'season')
on conflict (slug) do nothing;

-- ============================================================
-- ARTIST SPOTIFY CACHE (external-data cache, TTL) — backing store for v2.2
-- ============================================================
create table if not exists artist_spotify_cache (
  id            uuid primary key default uuid_generate_v4(),
  artist_id     uuid not null unique references artists(id) on delete cascade,
  spotify_id    text,
  followers     bigint,
  popularity    int,
  genres        text[] default '{}',
  image_url     text,
  preview_url   text,
  top_tracks    jsonb,
  raw           jsonb,
  fetched_at    timestamptz not null default now(),
  ttl_seconds   int not null default 604800,         -- 7 days
  expires_at    timestamptz,                          -- trigger-maintained: fetched_at + ttl_seconds
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- ============================================================
-- STAGES (per-festival stage coordinates) — backing store for v2.8
-- ============================================================
-- One row per distinct lineups.stage. v2.8 joins lineups.stage = stages.name.
-- coords_source: 'known' (published layout) | 'venue_centroid' (festival lat/lng spread).
create table if not exists stages (
  id            uuid primary key default uuid_generate_v4(),
  festival_id   uuid not null references festivals(id) on delete cascade,
  name          text not null,
  latitude      double precision,
  longitude     double precision,
  coords_source text,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  unique (festival_id, name)
);

-- ============================================================
-- SOURCES + INGESTION RUN-LOG (v3.0.1) — ingestion framework backing store
-- ============================================================
-- `sources`: the ingestion source registry. adapter_key → a Python SourceAdapter
-- (v3.0.2); adapter_type is the coarse kind; config carries per-source params so
-- adding a source is a row, not a code fork. trust = provenance label rows get
-- (same vocab as lineups.source) — free text so the vocab can grow.
create table if not exists sources (
  id           uuid primary key default uuid_generate_v4(),
  slug         text unique not null,
  name         text not null,
  adapter_type text not null check (adapter_type in ('scrape', 'api', 'manual')),
  adapter_key  text not null,
  config       jsonb not null default '{}'::jsonb,
  trust        text,
  enabled      boolean not null default true,
  schedule     text,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

-- `ingestion_runs`: one row per adapter invocation (run-log). The orchestrator
-- opens 'running' at start, closes with counts + per-stage errors. Spine for
-- v3.11 dashboards + v3.8 change-detection. festival_slug null = catalog-wide.
create table if not exists ingestion_runs (
  id             uuid primary key default uuid_generate_v4(),
  source_id      uuid references sources(id) on delete set null,
  festival_slug  text,
  status         text not null default 'running'
                   check (status in ('running', 'success', 'error', 'partial')),
  started_at     timestamptz not null default now(),
  finished_at    timestamptz,
  rows_upserted  int not null default 0,
  rows_skipped   int not null default 0,
  errors         jsonb not null default '[]'::jsonb,
  stats          jsonb not null default '{}'::jsonb,
  created_at     timestamptz default now()
);

-- Per-row provenance on lineups: which source row wrote it + a 0..1 confidence,
-- so v3.2's per-source conflict resolution has a key to coalesce-forward on.
-- Added after `sources` exists; ON DELETE SET NULL so dropping a source can't
-- cascade-delete real lineup rows. (lineups.source from v2.3.3 stays the trust label.)
alter table lineups add column if not exists source_id  uuid references sources(id) on delete set null;
alter table lineups add column if not exists confidence real;

-- ============================================================
-- INDEXES
-- ============================================================

-- Fuzzy search on festival + artist names
create index if not exists idx_festivals_name_trgm on festivals using gin (name gin_trgm_ops);
create index if not exists idx_artists_name_trgm   on artists  using gin (name gin_trgm_ops);

-- Tag array search
create index if not exists idx_festivals_tags on festivals using gin (tags);
create index if not exists idx_artists_tags   on artists  using gin (tags);
create index if not exists idx_artists_genres on artists  using gin (genres);

-- Lineup lookups
create index if not exists idx_lineups_festival on lineups (festival_id, year);
create index if not exists idx_lineups_artist   on lineups (artist_id);

-- Social posts by festival + platform
create index if not exists idx_social_festival_platform on social_posts (festival_id, platform, posted_at desc);

-- Festivals flagged with estimated dates (dashboard / data-quality sweeps) — added 20260610
create index if not exists idx_festivals_dates_estimated
  on festivals (dates_estimated) where dates_estimated = true;

-- Home / featured listing path: active festivals ordered by date (added v2.1.3)
create index if not exists idx_festivals_active_start on festivals (is_active, start_date);

-- Popularity sort for lineup/artist ranking (added v2.1.3)
create index if not exists idx_artists_popularity on artists (spotify_popularity desc nulls last);

-- Spotify cache stale-row sweeps (added v2.1.4)
create index if not exists idx_artist_spotify_cache_expires on artist_spotify_cache (expires_at);

-- Stage lookups by festival (added v2.3.4)
create index if not exists idx_stages_festival on stages (festival_id);

-- Ingestion run-log lookups (v3.0.1): recent runs per source + freshness per festival
create index if not exists idx_ingestion_runs_source_started
  on ingestion_runs (source_id, started_at desc);
create index if not exists idx_ingestion_runs_festival_started
  on ingestion_runs (festival_slug, started_at desc) where festival_slug is not null;

-- ============================================================
-- FULL-TEXT SEARCH FUNCTION
-- Supports searching by festival name, city, tag, genre, artist name
-- ============================================================
create or replace function search_all(query text)
returns table (
  type        text,
  id          uuid,
  slug        text,
  name        text,
  description text,
  score       float
) as $$
  -- v3.3: weighted ranking — name/city trigram similarity boosted by upcoming
  -- recency (festivals) and Spotify popularity (artists). See migration
  -- 20260626_v3_3_search_ranking.sql.
  select 'festival'::text as type, f.id, f.slug, f.name, f.description,
         greatest(similarity(f.name, query), similarity(coalesce(f.city, ''), query))
           * (case when f.start_date >= current_date then 1.25
                   when f.start_date is null then 1.0
                   else 0.85 end) as score
  from festivals f
  where (f.name % query or f.city % query or f.tags @> array[lower(query)])
    and f.is_active
  union all
  select 'artist'::text, a.id, a.slug, a.name, a.bio,
         similarity(a.name, query)
           * (0.8 + 0.4 * coalesce(a.spotify_popularity, 0) / 100.0) as score
  from artists a
  where a.name % query or a.genres @> array[lower(query)]
  order by score desc
  limit 25;
$$ language sql stable;

-- "Did you mean?" — closest few names ignoring the % threshold (v3.3 zero-result UX).
create or replace function search_suggest(query text)
returns table (type text, slug text, name text, score float) as $$
  select 'festival'::text, f.slug, f.name, similarity(f.name, query) as score
  from festivals f where f.is_active
  union all
  select 'artist'::text, a.slug, a.name, similarity(a.name, query)
  from artists a
  order by score desc
  limit 3;
$$ language sql stable;

-- ============================================================
-- VIEWS
-- ============================================================

-- Upcoming, active festivals with date-status — dashboard helper (added 20260610).
create or replace view v_upcoming_festivals as
  select
    id, slug, name, city, state,
    start_date, end_date, dates_estimated,
    tags, accent_color, hero_image_url, vector_art, is_active
  from festivals
  where is_active = true
    and (start_date is null or start_date >= current_date - interval '30 days')
  order by start_date asc nulls last, name;

-- ============================================================
-- ROW LEVEL SECURITY (public read, service role write)
-- ============================================================
alter table festivals    enable row level security;
alter table artists      enable row level security;
alter table lineups      enable row level security;
alter table media        enable row level security;
alter table social_posts enable row level security;
alter table fun_facts    enable row level security;
alter table tags         enable row level security;
alter table artist_spotify_cache enable row level security;
alter table stages       enable row level security;
alter table sources        enable row level security;
alter table ingestion_runs enable row level security;

-- Public read policies
create policy "Public read festivals"    on festivals    for select using (true);
create policy "Public read artists"      on artists      for select using (true);
create policy "Public read lineups"      on lineups      for select using (true);
create policy "Public read media"        on media        for select using (true);
create policy "Public read social_posts" on social_posts for select using (true);
create policy "Public read fun_facts"    on fun_facts    for select using (true);
create policy "Public read tags"         on tags         for select using (true);
create policy "Public read artist_spotify_cache" on artist_spotify_cache for select using (true);
create policy "Public read stages"       on stages       for select using (true);
create policy "Public read sources"        on sources        for select using (true);
create policy "Public read ingestion_runs" on ingestion_runs for select using (true);

-- ============================================================
-- UPDATED_AT triggers
-- ============================================================
create or replace function set_updated_at()
returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql;

create trigger festivals_updated_at before update on festivals
  for each row execute function set_updated_at();

create trigger artists_updated_at before update on artists
  for each row execute function set_updated_at();

-- artist_spotify_cache maintains expires_at (= fetched_at + ttl_seconds) and
-- updated_at via a trigger — timestamptz+interval is STABLE, so it can't be a
-- GENERATED column.
create or replace function set_artist_cache_expiry()
returns trigger as $$
begin
  new.expires_at := new.fetched_at + make_interval(secs => new.ttl_seconds);
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

create trigger artist_spotify_cache_expiry
  before insert or update on artist_spotify_cache
  for each row execute function set_artist_cache_expiry();

-- Conflict policy (v2.3.3): a lower-trust writer must never clobber a verified
-- lineup row. The ON CONFLICT DO UPDATE fires this; returning OLD no-ops the
-- update for verified rows. One DB rule covers every writer.
create or replace function protect_verified_lineups()
returns trigger as $$
begin
  if old.source in ('official', 'wikipedia')
     and (new.source is null or new.source not in ('official', 'wikipedia')) then
    return old;
  end if;
  return new;
end;
$$ language plpgsql;

create trigger lineups_protect_verified
  before update on lineups
  for each row execute function protect_verified_lineups();

-- INSERT-path half of the conflict policy (v2.3.6): a non-verified source can't
-- add a new row for an artist/year a verified source already covers.
create or replace function skip_unverified_insert()
returns trigger as $$
begin
  if (new.source is null or new.source not in ('official', 'wikipedia'))
     and exists (
       select 1 from lineups l
       where l.festival_id = new.festival_id
         and l.artist_id = new.artist_id
         and l.year = new.year
         and l.source in ('official', 'wikipedia')
     ) then
    return null;
  end if;
  return new;
end;
$$ language plpgsql;

create trigger lineups_skip_unverified_insert
  before insert on lineups
  for each row execute function skip_unverified_insert();

create trigger stages_updated_at before update on stages
  for each row execute function set_updated_at();

create trigger sources_updated_at before update on sources
  for each row execute function set_updated_at();
